package fatec.ph.les;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

public class CadastroclienteTest {
  private WebDriver driver;
  JavascriptExecutor js;

  @Before
  public void setUp() {

    System.setProperty("webdriver.chrome.driver",
        "src/test/resources/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void cadastrocliente() {
    try {

      driver.get("http://localhost:8080/");
      Thread.sleep(100);
      driver.manage().window().setSize(new Dimension(1552, 840));
      driver.findElement(By.linkText("Login")).click();
      driver.findElement(By.id("email")).click();
      driver.findElement(By.linkText("Register")).click();
      driver.findElement(By.id("nome")).click();
      driver.findElement(By.id("nome")).sendKeys("21");
      driver.findElement(By.id("datanasc")).click();
      driver.findElement(By.id("datanasc")).sendKeys("0002-02-22");
      driver.findElement(By.id("datanasc")).sendKeys("0020-02-22");
      driver.findElement(By.id("datanasc")).sendKeys("0200-02-22");
      driver.findElement(By.id("datanasc")).sendKeys("2002-02-22");
      driver.findElement(By.id("gen")).click();
      {
        WebElement dropdown = driver.findElement(By.id("gen"));
        dropdown.findElement(By.xpath("//option[. = 'Masculino']")).click();
      }
      driver.findElement(By.id("email")).click();
      driver.findElement(By.id("email")).sendKeys("21@2");
      driver.findElement(By.id("password")).click();
      driver.findElement(By.id("password")).sendKeys("22");
      driver.findElement(By.cssSelector("button")).click();
      driver.findElement(By.id("cep")).click();
      driver.findElement(By.id("cep")).sendKeys("08780690");
      Thread.sleep(500);

      driver.findElement(By.id("numero")).click();
      driver.findElement(By.id("numero")).sendKeys("1");
      driver.findElement(By.id("complemento")).click();
      driver.findElement(By.id("complemento")).sendKeys("1");
      driver.findElement(By.id("tiporesidencia")).click();
      {
        WebElement dropdown = driver.findElement(By.id("tiporesidencia"));
        dropdown.findElement(By.xpath("//option[. = 'Casa']")).click();
      }
      driver.findElement(By.id("save-btn")).click();
      driver.findElement(By.id("bandeira")).click();
      {
        WebElement dropdown = driver.findElement(By.id("bandeira"));
        dropdown.findElement(By.xpath("//option[. = 'Mastercard']")).click();
      }
      driver.findElement(By.id("ncartao")).click();
      driver.findElement(By.id("ncartao")).sendKeys("22");
      driver.findElement(By.id("nomeCli")).click();
      driver.findElement(By.id("nomeCli")).sendKeys("pedro");
      driver.findElement(By.id("cv")).click();
      driver.findElement(By.id("cv")).sendKeys("223");
      driver.findElement(By.id("save-btn")).click();
      driver.findElement(By.cssSelector("html")).click();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
