package fatec.ph.les;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class MultiploscartoesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
        "src/test/driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void multiploscartoes() {
    try {
      driver.get("http://localhost:8080/");
      Thread.sleep(100);
      driver.manage().window().setSize(new Dimension(1536, 824));
      driver.findElement(By.linkText("Shop")).click();
      driver.findElement(By.linkText("Learn More")).click();
      driver.findElement(By.id("plus2")).click();
      driver.findElement(By.id("livrolink")).click();
      driver.findElement(By.cssSelector(".fa-shopping-cart")).click();
      driver.findElement(By.id("endereco")).click();
      driver.findElement(By.id("endereco")).click();
      Thread.sleep(100);
      Actions actions = new Actions(driver);
      {
        WebElement dropdown = driver.findElement(By.id("cartoes-btn"));
        actions.moveToElement(dropdown).build().perform();
      }
      Thread.sleep(1000);
      driver.findElement(By.linkText("212")).click();
      driver.findElement(By.id("save-btn")).click();
      driver.findElement(By.cssSelector("a:nth-child(4)")).click();
      driver.findElement(By.id("ordem-tab")).click();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
