package fatec.ph.les;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class MultiplositensTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  // C:\Users\Pedro
  // Henrique\Documents\Fatec\les\lesapp\lesapp\src\test\java\fatec\ph\les

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
        "src/test/driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void multiplositens() {
    try {
      driver.get("http://localhost:8080/");
      Thread.sleep(100);
      driver.manage().window().setSize(new Dimension(1536, 824));
      driver.findElement(By.linkText("Shop")).click();
      driver.findElement(By.linkText("Learn More")).click();
      driver.findElement(By.id("plus2")).click();
      driver.findElement(By.id("livrolink")).click();
      driver.findElement(By.cssSelector(".arrivals_btn")).click();
      driver.findElement(By.id("plus1")).click();
      driver.findElement(By.id("livrolink")).click();
      driver.findElement(By.cssSelector(".fa-shopping-cart")).click();
      driver.findElement(By.id("save-btn")).click();
      driver.findElement(By.cssSelector(".fa-user")).click();
      driver.findElement(By.id("ordem-tab")).click();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
