package fatec.ph.les;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;

public class NovocartaoenderecoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver",
        "src/test/driver/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void novocartaoendereco() {
    try {
      driver.get("http://localhost:8080/");
      Thread.sleep(100);
      driver.manage().window().setSize(new Dimension(1536, 824));
      driver.findElement(By.linkText("Shop")).click();
      driver.findElement(By.linkText("Learn More")).click();
      driver.findElement(By.id("plus2")).click();
      driver.findElement(By.id("livrolink")).click();
      driver.findElement(By.cssSelector(".fa-shopping-cart")).click();
      driver.findElement(By.cssSelector("form:nth-child(2) > .dropbtn")).click();

      Thread.sleep(100);
      driver.findElement(By.id("cep")).click();
      driver.findElement(By.id("cep")).sendKeys("08780690");
      Thread.sleep(2000);
      driver.findElement(By.id("numero")).click();
      driver.findElement(By.id("numero")).sendKeys("44");
      Thread.sleep(100);
      driver.findElement(By.id("complemento")).click();
      driver.findElement(By.id("complemento")).sendKeys("44");
      Thread.sleep(100);
      driver.findElement(By.id("tiporesidencia")).click();
      {
        WebElement dropdown = driver.findElement(By.id("tiporesidencia"));
        dropdown.findElement(By.xpath("//option[. = 'Condominio']")).click();
      }
      driver.findElement(By.id("save-btn")).click();

      driver.findElement(By.id("endereco")).click();
      {
        WebElement dropdown = driver.findElement(By.id("endereco"));
        Thread.sleep(1000);
        dropdown.findElement(By.xpath("//option[. = 'Jardim Armênia  44']")).click();
      }
      Thread.sleep(1000);
      Actions actions = new Actions(driver);
      {
        WebElement dropdown = driver.findElement(By.id("cartoes-btn"));
        actions.moveToElement(dropdown).build().perform();
      }
      Thread.sleep(1000);
      driver.findElement(By.linkText("Cadastrar Cartao")).click();
      driver.findElement(By.id("bandeira")).click();
      {
        WebElement dropdown = driver.findElement(By.id("bandeira"));
        dropdown.findElement(By.xpath("//option[. = 'Elo']")).click();
      }

      Thread.sleep(100);
      driver.findElement(By.id("nomeCli")).click();
      driver.findElement(By.id("nomeCli")).sendKeys("33");
      Thread.sleep(100);

      driver.findElement(By.id("ncartao")).click();
      driver.findElement(By.id("ncartao")).sendKeys("999");

      Thread.sleep(100);
      driver.findElement(By.id("cv")).click();
      driver.findElement(By.id("cv")).sendKeys("123");

      Thread.sleep(100);
      driver.findElement(By.id("save-btn")).click();

      driver.findElement(By.id("endereco")).click();
      {
        WebElement dropdown = driver.findElement(By.id("endereco"));
        Thread.sleep(1000);
        dropdown.findElement(By.xpath("//option[. = 'Jardim Armênia  44']")).click();
      }

      driver.findElement(By.id("save-btn")).click();

      driver.findElement(By.cssSelector(".fa-user")).click();
      driver.findElement(By.id("ordem-tab")).click();
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
  }
}
